# {% include './common.yaml' %}

assets_subdir: "dark"
background_color: "{{ palette.gray1 }}"
background_color_alt: "{{ palette.gray2 }}"
background_color_alt2: "{{ palette.black }}"
background_color_alt3: "{{ palette.gray_light }}"
background_color_disabled: "#181818"
border_color: "{{ palette.gray5 }}"
button_pressed: "#2d2d2d"
checkbox_check: "{{ palette.white }}"
combobox: "#1f1f27"
highlight: "{{ palette.white }}"
hscrollbar: "{{ palette.gray3 }}"
hscrollbar_groove: "{{ palette.black }}"
item_handle: "#aaaaaa"
text_background_color: "{{ palette.black_light }}"
text_color: "{{ palette.white }}"
text_color_alt: "{{ palette.black }}"
text_color_disabled: "#d0d0d0"
tab_selected: "#1e1e1e"
track_panel_background: "{{ palette.gray4 }}"
transport_clock_background: "#1e1e1e"
transport_panel_background: "{{ palette.gray_light }}"
vscrollbar: "{{ palette.gray3 }}"
vscrollbar_groove: "{{ palette.black }}"
