daw:
  # Item editor CC/pitchbend automation point
  item_atm_point: "#f00e0e"
  # The pen drawing the outline of an item editor CC/pitchbend automation point
  item_atm_point_pen: "#d00e0e"
  # Item editor selected CC/pitchbend automation point
  item_atm_point_selected: "#f0f0f0"
  # Item editor audio item handle
  item_audio_handle: "{{ item_handle }}"
  # Item editor selected audio item handle
  item_audio_handle_selected: "#181818"
  # The horizontal line that is drawn on audio items during
  # volume manipulation using mouse click+drag with
  # modifier keys.  The item will be selected, so this color
  # must contrast with the selected audio item color
  item_audio_vol_line: "#ff0000"
  # The text on an audio item that displays data such as file
  # name, and volume during mouse modifier operations.  The item
  # will be selected, this color must contrast with the selected
  # audio item color
  item_audio_label: "{{ text_color }}"
  # The text on an audio item that displays data such as file name, and volume
  # during mouse modifier operations.  The item will be selected, this color
  # must contrast with the selected color
  item_audio_label_selected: "{{ text_color_alt }}"
  # The color used to draw the audio file waveform onto the audio item
  item_audio_waveform: "{{ background_color_alt }}"
  # The background of the note editor for the keys that are not part of
  # the current scale
  note_black_background: "{{ palette.black }}"
  # The background of the note editor for the root key of the current scale
  note_root_background: "#401e1e"
  # The background of the note editor for the keys that are part of the
  # current scale
  note_white_background: "{{ palette.gray3 }}"
  # The vertical lines drawn between beats according to snap settings
  # ie: 1/16th, 1/8th note, etc...
  note_snap_line: "{{ palette.black }}"
  # The vertical line drawn at each beat
  note_beat_line: "{{ palette.black }}"
  # The color of a selected note
  note_selected_color: "#cccccc"
  # The color of the note when velocity is at max value
  note_vel_max_color: "#f89e19"
  # The color of the note when velocity is at min value
  note_vel_min_color: "#7777b9"
  # The sequencer playback cursor
  playback_cursor: "{{ palette.white }}"
  # Enable antialiasing for the sequencer
  seq_antialiasing: false
  # Sequencer automation points
  seq_atm_item: '{{ palette.white }}'
  # Selected sequencer automation points
  seq_atm_item_selected: '{{ palette.black }}'
  # Sequencer automation lines
  seq_atm_line: '{{ palette.white }}'
  # Sequencer QGraphicsScene background
  seq_background: "{{ palette.gray5 }}"
  # The background fill color of the sequencer items
  # If seq_item_background_use_track_color == true, the track color will be
  # used, and this value should be set to something with transparency
  seq_item_background: "{{ background_color }}"
  # Use the track color instead of seq_item_background
  seq_item_background_use_track_color: false
  # Vertical bar lines in the sequencer
  seq_bar_line: "#090909"
  # Vertical beat lines in the sequencer
  seq_beat_line: "#4c4d4d"
  # Vertical 16th note lines in the sequencer
  seq_16th_line: "#090909"
  # Sequencer header
  seq_header: "#1d1e22"
  # Sequencer header context menu event position marker
  seq_header_event_pos: "#cccccc"
  # Sequencer header region
  seq_header_region: "#6212a2"
  # Sequencer header text
  seq_header_text: "{{ text_color }}"
  # Sequencer item handle
  seq_item_handle: "{{ item_handle }}"
  # Sequencer selected item handle
  seq_item_handle_selected: "{{ palette['gray5'] }}"
  # Used to paint audio on sequencer items
  seq_item_audio: "#969696"
  # Used to paint notes on sequencer items
  seq_item_note: "#a5a5a5"
  # The label text for sequencer items
  seq_item_text: "{{ text_color }}"
  # The label text for selected sequencer items
  seq_item_text_selected: "{{ palette.black }}"
  # Selected sequencer items
  seq_selected_item: "{{ palette.white }}"
  # Sequencer tempo marker
  seq_tempo_marker: "{{ palette.white }}"
  # Horizontal track lines in the sequencer
  seq_track_line: "#090909"
  # The silhouette when dragging an item onto a view
  drag_drop_silhouette: "#6212a2"
  # Default track colors, also applies to audio item editor
  track_default_colors:
    - "#157519"
    - "#19656e"
    - "#195585"
    - "#293075"
    - "#511965"
    - "#55193e"
widgets:
  # The color that audio files are drawn with in the sampler and wave editor
  audio_item_viewer_color: "{{ palette.purple }}"
  # The default QGraphicsScene background color used by the widgets library
  default_scene_background: "{{ palette.gray5  }}"
  # Used to draw the arc around the knob
  knob_arc_pen: "{{ palette.purple }}"
  # Used to draw the knob background
  knob_arc_background_pen: "#5a5a5a"
  # The knob background image
  knob_bg_image: "knob-bg.svg"
  # The knob image.  Will be rotated as the knob moves
  knob_fg_image: "knob-fg.svg"
  # The gradient used to draw peak meters.  See sglib.models.theme.Gradient
  peak_meter:
    stops:
      - pos: 0.0
        color: "#cc2233"
      - pos: 0.0333
        color: "#aa22bb"
      - pos: 0.3
        color: "#772288"
      - pos: 0.9
        color: "#442266"
  # The color of a playback cursor line
  playback_cursor: "{{ palette.white }}"
  # Routing graph widget node
  rout_graph_node: "#b86e19"
  # Routing graph widget node text
  rout_graph_node_text: "{{ palette.white }}"
  # Routing graph widget to node when mouse hovering
  rout_graph_to: "#b76060"
  # Routing graph widget from node when mouse hovering
  rout_graph_from: "#6060b7"
  # Routing graph widget matrix lines
  rout_graph_lines: "#696969"
  # Routing graph wires connecting audio
  rout_graph_wire_audio: "#44aa44"
  # Routing graph wires connecting midi
  rout_graph_wire_midi: "#4444aa"
  # Routing graph wires connecting audio sidechain inputs
  rout_graph_wire_sc: "#aa4444"
  # Splash screen shown at start up
  splash_screen: "splash.svg"
  # Text status messages on splash screen shown at start up
  splash_screen_text: "{{ text_color }}"
